
# logger options
image_save_iter: 10000        # How often do you want to save output images during training
snapshot_save_iter: 10000     # How often do you want to save trained models
log_iter: 4                  # How often do you want to log the training stats
test_iter: 2                  # How ofter do you want to evaluate the model

# optimization options
n_epochs: 600                 # number of training epochs
batch_size: 32                # batch size
weight_decay: 0.0001          # weight decay
init: kaiming                 # initialization [gaussian/kaiming/xavier/orthogonal]
lr: 0.001                      # initial learning rate
lr_policy: step               # learning rate scheduler
step_size: 100000             # how often to decay learning rate


# model options
model_name: resnet34           # the model name of a DNN
pretrained: False              # the model name of a DNN
n_classes: 13                  # the number of classification sorts

# data options
input_dim: 3                                # number of image channels [1/3]
num_workers: 0                              # number of data loading threads
new_size: 250                               # first resize the shortest image side to this size
crop_image_height: 224                      # random crop image of this height
crop_image_width: 224                       # random crop image of this width
data_root: dataset/GTSRB-new                # dataset folder location
